### ISSUE TITLE
What dataset is used?

### ISSUE THREAD

**Issue by rickymedrano** [NVIDIA-AI-IOT/jetson_benchmarks#14]
Which dataset is used when it's benchmarking the yolov3 model? I'm confused how it exactly it's calculating the FPS.

**Comment by ak-nv** [comment]
We use `trtexec` tool from [NVIDIA TensorRT](https://developer.nvidia.com/tensorrt) to get execution time. For YoloV3, we use original model trained on and convert ONNX, please check [JK Jung's blog post](https://jkjung-avt.github.io/tensorrt-yolov3/) .
