### ISSUE TITLE
Error when running on Jetson nano

### ISSUE THREAD

**Issue by Lenni** [NVIDIA-AI-IOT/jetson_benchmarks#36]
When I tried to run the benchmarking script on the Jetson Nano, I get the following Error:

```
jetson@jetson ~/jetson_benchmarks> sudo python3 benchmark.py --all --csv_file_path ./benchmark_csv/tx2-nano-benchmarks.csv --model_dir ./models --jetson_devkit nano --gpu_freq 921600000 --power_mode 0 --precisio
n fp16
Please close all other applications and Press Enter to continue...
Setting Jetson nano in max performance mode
Traceback (most recent call last):
  File "benchmark.py", line 130, in <module>
    main()
  File "benchmark.py", line 28, in main
    system_check.run_set_clocks_withDVFS()
  File "/home/jetson/jetson_benchmarks/utils/utilities.py", line 37, in run_set_clocks_withDVFS
    self.set_clocks_withDVFS(frequency=self.gpu_freq, device='gpu')
  File "/home/jetson/jetson_benchmarks/utils/utilities.py", line 74, in set_clocks_withDVFS
    from_freq = self.read_internal_register(register=freq_register_, device=device)
  File "/home/jetson/jetson_benchmarks/utils/utilities.py", line 100, in read_internal_register
    reg_read = open(register, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/gpu.0/devfreq/57000000.gpunafll_gpc0/rate'

```

**Comment by alinden429** [comment]
I also get this error. 

`mic-710ai@ubuntu:~/Desktop/benchmark/jetson_benchmarks$ sudo python3 benchmark.py --all --csv_file_path /benchmark_csv/tx2-nano-benchmarks.csv --model_dir /Desktop/benchmark/jetson_benchmarks/models/ --jetson_devkit nano --gpu_freq 921600000 --power_mode 0 --precision fp16
Please close all other applications and Press Enter to continue...
Setting Jetson nano in max performance mode
Traceback (most recent call last):
  File "benchmark.py", line 130, in <module>
    main()
  File "benchmark.py", line 28, in main
    system_check.run_set_clocks_withDVFS()
  File "/home/mic-710ai/Desktop/benchmark/jetson_benchmarks/utils/utilities.py", line 37, in run_set_clocks_withDVFS
    self.set_clocks_withDVFS(frequency=self.gpu_freq, device='gpu')
  File "/home/mic-710ai/Desktop/benchmark/jetson_benchmarks/utils/utilities.py", line 74, in set_clocks_withDVFS
    from_freq = self.read_internal_register(register=freq_register_, device=device)
  File "/home/mic-710ai/Desktop/benchmark/jetson_benchmarks/utils/utilities.py", line 100, in read_internal_register
    reg_read = open(register, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/gpu.0/devfreq/57000000.gpunafll_gpc0/rate'
`

Jetson_release
`mic-710ai@ubuntu:~/Desktop/benchmark/jetson_benchmarks$ jetson_release
Software part of jetson-stats 4.1.5 - (c) 2023, Raffaello Bonghi
Model: NVIDIA Jetson Nano Developer Kit - Jetpack 4.6 [L4T 32.6.1]
NV Power Mode: MAXN - Type: 0
jtop:
 - Version: 4.1.5
 - Service: Active
Libraries:
 - CUDA: 10.2.300
 - cuDNN: 8.2.1.32
 - TensorRT: 8.0.1.6
 - VPI: 1.1.12
 - Vulkan: 1.2.70
 - OpenCV: 4.1.1 - with CUDA: NO
`

**Comment by AsawareeBhide** [comment]
Hi! Could you please try adding `--jetson_clocks` to the command? For example:

`sudo python3 benchmark.py --all --csv_file_path /benchmark_csv/tx2-nano-benchmarks.csv --model_dir /Desktop/benchmark/jetson_benchmarks/models/ --jetson_devkit nano --gpu_freq 921600000 --power_mode 0 --precision fp16  --jetson_clocks`

**Comment by janezlapajne** [comment]
Yep, it works by adding this flag.
