### ISSUE TITLE
Unknown argument: --explicitBatch

### ISSUE THREAD

**Issue by zabir-nabil** [NVIDIA-AI-IOT/jetson_benchmarks#9]
I was able to build but after running bechmark.py I get the following error:
```
Please close all other applications and Press Enter to continue...
Setting Jetson nano in max performance mode
gpu frequency is set from 76800000 Hz --> to 921600000 Hz
------------Executing yolov3-tiny-416------------

Error in Build, Please check the log in: /home/tigerit/nabil/jetson_benchmarks/
We recommend to run benchmarking in headless mode
--------------------------

Model Name: yolov3-tiny-416
FPS:0.00

--------------------------
```

Details about my nano:

```
NVIDIA Jetson Nano (Developer Kit Version)
 L4T 32.1.0 [ JetPack 4.2 ]
   Ubuntu 18.04.2 LTS
   Kernel Version: 4.9.140-tegra
 CUDA 10.0.166
   CUDA Architecture: 5.3
 OpenCV version: 3.3.1
   OpenCV Cuda: NO
 CUDNN: 7.3.1.28
 TensorRT: 5.0.6.3
 Vision Works: 1.6.0.500n
 VPI: NOT_INSTALLED

```

**Comment by ak-nv** [comment]
The repo is targeted for JP4.4 and with TensorRT 7. 
Following suggestions might be worth trying if TRT5 needs to be used:
1. Please change read_perf_time function such that it captures right regex: https://github.com/NVIDIA-AI-IOT/jetson_benchmarks/blob/master/utils/read_write_data.py#L71
2. You can try commenting model.remove from [benchmark.py](https://github.com/NVIDIA-AI-IOT/jetson_benchmarks/blob/master/benchmark.py) and check the log in model_dir; (Once model completed run, it will generate log file by name <model><batch_size><workspace_size><accelerator>.txt
